export const EMPTY_DESIGN = {
    assumptions: '', classes: '', responsibilities: '', interfaces: '', relationships: '', mainFlow: '', patterns: '', edgeCases: '', extensibility: '', tradeoffs: ''
};
export const problems = [
    { id: 'parking-lot', title: 'Parking Lot', description: 'Design a parking facility that assigns vehicles to suitable spots and calculates fees while remaining easy to extend.', difficulty: 'Beginner', suggestedTime: 35, requirements: ['Support cars, motorcycles, and trucks.', 'Assign an available compatible spot on entry.', 'Release a spot on exit and calculate a fee.', 'Support multiple floors and spot sizes.', 'Keep pricing rules replaceable.'], assumptions: ['One entrance and exit flow is enough for the MVP.', 'No payment gateway is required.', 'A vehicle has one active ticket at a time.'], guidance: ['Start by identifying ownership of parking state.', 'Keep pricing policy separate from allocation policy.', 'Think about what changes when a new vehicle type is added.'] },
    { id: 'elevator-system', title: 'Elevator System', description: 'Model elevators that respond to requests, move between floors, and coordinate scheduling.', difficulty: 'Intermediate', suggestedTime: 45, requirements: ['Accept hall and car calls.', 'Track elevator direction and current floor.', 'Dispatch an appropriate elevator.', 'Open doors safely at requested floors.', 'Allow scheduling strategy to evolve.'], assumptions: ['Travel time and hardware integration are out of scope.', 'One building has several elevators.', 'Requests can be represented as immutable commands.'], guidance: ['Separate request coordination from elevator state.', 'Make dispatch policy a replaceable decision.', 'Describe invalid transitions and safety checks.'] },
    { id: 'vending-machine', title: 'Vending Machine', description: 'Design a vending machine that manages inventory, payments, selection, and change.', difficulty: 'Beginner', suggestedTime: 30, requirements: ['Display available products and prices.', 'Accept coins or a payment abstraction.', 'Dispense an in-stock selection.', 'Return change and handle cancellation.', 'Reject invalid selections and insufficient payment.'], assumptions: ['Exact coin denominations are configurable.', 'The machine can report out-of-stock products.', 'Hardware dispensing is represented by an interface.'], guidance: ['A state model can make the purchase flow explicit.', 'Keep inventory and payment concerns separate.', 'Explain how a failed dispense affects the transaction.'] },
    { id: 'library-management', title: 'Library Management System', description: 'Design lending operations for books, members, reservations, and overdue policies.', difficulty: 'Advanced', suggestedTime: 50, requirements: ['Search books and track physical copies.', 'Issue and return copies for members.', 'Support reservations and waitlists.', 'Calculate overdue fines with a policy.', 'Prevent invalid borrowing operations.'], assumptions: ['A member may borrow a limited number of copies.', 'Notifications can be represented as a port.', 'Fine calculation rules may change over time.'], guidance: ['Model book metadata separately from physical copies.', 'Define invariants around availability and reservations.', 'Use policies for limits and fines rather than conditionals everywhere.'] }
];
